# language: haskell

env:
 - GHCVER=7.10.3 CABALVER=1.24
 - GHCVER=8.0.2 CABALVER=1.24
 - GHCVER=8.2.2 CABALVER=1.24
 - GHCVER=7.10.3 CABALVER=2.0
 - GHCVER=8.0.2 CABALVER=2.0
 - GHCVER=8.2.2 CABALVER=2.0

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/cabal/$CABALVER/bin:/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal update
 - cabal install --only-dependencies

script:
 - cabal configure
 - cabal build
